### PR TITLE
Delphi/FPC Cross Support

### PR DESCRIPTION
**Pull request by TetzkatLipHoka**
Delphi/FPC Cross Support
Delphi Theme Support
Offset-Property
UInt64 Offsets

### CODE REVIEW

**Comment by michalgw** [comment]
Thanks for your contribution, but after your changes MPHexEdit no longer compiles in FPC/Lazarus. Could you check and improve FPC/Lazarus compatibility?

**Comment by TetzkatLipHoka** [comment]
What exactly is causing the issue?
As I dont use FPC at all was a 'cold fusion' of your latest Version and mine.
If you let me know whats the issue I'll try to fix it.

**Comment by michalgw** [comment]
Most errors are related to the $IF directive: `{$IF CompilerVersion < 23}`

Line 3527 of MPHexEditor.pas contains unnecessary "then" https://github.com/michalgw/mphexeditor/blob/0bfdb2a755baeb83b32ab8cc0b163e7d934f8088/src/MPHexEditor.pas#L3525-L3531

Lazarus does not know these functions: MultiByteToWideChar, GetTextExtentPoint32W, ExtTextOutW

Below is a list of all compilation errors:
- mphexeditor.pas(2241,5) Error: Incompatible types: got "AnsiString(0)" expected "Int64"
- mphexeditor.pas(2241,5) Error: Compile time expression: Wanted Boolean but got <erroneous type> at IF or ELSEIF
- mphexeditor.pas(3530,12) Error: Illegal expression
- mphexeditor.pas(3531,5) Error: Syntax error, ";" expected but "identifier RESULT" found
- mphexeditor.pas(5741,7) Error: Incompatible types: got "AnsiString(0)" expected "Int64"
- mphexeditor.pas(5741,7) Error: Compile time expression: Wanted Boolean but got <erroneous type> at IF or ELSEIF
- mphexeditor.pas(5767,7) Error: Incompatible types: got "AnsiString(0)" expected "Int64"
- mphexeditor.pas(5767,7) Error: Compile time expression: Wanted Boolean but got <erroneous type> at IF or ELSEIF
- mphexeditor.pas(5933,7) Error: Incompatible types: got "AnsiString(0)" expected "Int64"
- mphexeditor.pas(5933,7) Error: Compile time expression: Wanted Boolean but got <erroneous type> at IF or ELSEIF
- mphexeditor.pas(5935,7) Error: Incompatible types: got "AnsiString(0)" expected "Int64"
- mphexeditor.pas(5935,7) Error: Compile time expression: Wanted Boolean but got <erroneous type> at IF or ELSEIF
- mphexeditor.pas(5940,7) Error: Incompatible types: got "AnsiString(0)" expected "Int64"
- mphexeditor.pas(5940,7) Error: Compile time expression: Wanted Boolean but got <erroneous type> at IF or ELSEIF
- mphexeditor.pas(5946,7) Error: Incompatible types: got "AnsiString(0)" expected "Int64"
- mphexeditor.pas(5946,7) Error: Compile time expression: Wanted Boolean but got <erroneous type> at IF or ELSEIF
- mphexeditor.pas(6586,13) Error: Incompatible types: got "AnsiString(0)" expected "Int64"
- mphexeditor.pas(6586,13) Error: Compile time expression: Wanted Boolean but got <erroneous type> at IF or ELSEIF
- mphexeditor.pas(6593,13) Error: Incompatible types: got "AnsiString(0)" expected "Int64"
- mphexeditor.pas(6593,13) Error: Compile time expression: Wanted Boolean but got <erroneous type> at IF or ELSEIF
- mphexeditor.pas(6606,9) Error: Incompatible types: got "AnsiString(0)" expected "Int64"
- mphexeditor.pas(6606,9) Error: Compile time expression: Wanted Boolean but got <erroneous type> at IF or ELSEIF
- mphexeditor.pas(6608,9) Error: Incompatible types: got "AnsiString(0)" expected "Int64"
- mphexeditor.pas(6608,9) Error: Compile time expression: Wanted Boolean but got <erroneous type> at IF or ELSEIF
- mphexeditor.pas(6752,9) Error: Incompatible types: got "AnsiString(0)" expected "Int64"
- mphexeditor.pas(6752,9) Error: Compile time expression: Wanted Boolean but got <erroneous type> at IF or ELSEIF
- mphexeditor.pas(6754,9) Error: Incompatible types: got "AnsiString(0)" expected "Int64"
- mphexeditor.pas(6754,9) Error: Compile time expression: Wanted Boolean but got <erroneous type> at IF or ELSEIF
- mphexeditor.pas(6820,28) Error: Identifier not found "MultiByteToWideChar"
- mphexeditor.pas(6822,28) Error: Identifier not found "MultiByteToWideChar"
- mphexeditor.pas(6837,11) Error: Identifier not found "MultiByteToWideChar"
- mphexeditor.pas(6839,41) Error: Incompatible types: got "AnsiString(0)" expected "Int64"
- mphexeditor.pas(6839,41) Error: Compile time expression: Wanted Boolean but got <erroneous type> at IF or ELSEIF
- mphexeditor.pas(6841,11) Error: Identifier not found "MultiByteToWideChar"
- mphexeditor.pas(6925,46) Error: Identifier not found "GetTextExtentPoint32W"
- mphexeditor.pas(6928,11) Error: Identifier not found "ExtTextOutW"
- mphexeditor.pas(7517,9) Error: Incompatible types: got "AnsiString(0)" expected "Int64"
- mphexeditor.pas(7517,9) Error: Compile time expression: Wanted Boolean but got <erroneous type> at IF or ELSEIF
- mphexeditor.pas(7519,9) Error: Incompatible types: got "AnsiString(0)" expected "Int64"
- mphexeditor.pas(7519,9) Error: Compile time expression: Wanted Boolean but got <erroneous type> at IF or ELSEIF
- mphexeditor.pas(7535,9) Error: Incompatible types: got "AnsiString(0)" expected "Int64"
- mphexeditor.pas(7535,9) Error: Compile time expression: Wanted Boolean but got <erroneous type> at IF or ELSEIF
- mphexeditor.pas(7537,9) Error: Incompatible types: got "AnsiString(0)" expected "Int64"
- mphexeditor.pas(7537,9) Error: Compile time expression: Wanted Boolean but got <erroneous type> at IF or ELSEIF

**Comment by TetzkatLipHoka** [comment]
I updated again, try your luck :P
I wrapped all the 1118 fixes in IFNDEF FPC, hope thats enough to stop FPC from trying to evaluate them.

**Comment by michalgw** [comment]
I have to reject your request because after these changes it is still not possible to build under FPC/Lazarus. Please fix Lazarus compatibility and make a new request because Lazarus compatibility is a priority. If you do not need Lazarus compatibility then consider using a repository focused on the Delphi version, such as: https://github.com/zhugecaomao/HexEditor

**Pull request closed without merging**
